image: ${CI_REGISTRY}/molpro/docker

job:
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l); echo $procs processors available
    - TOP=$PWD
    - cd $TOP; BUILD=build/$(git rev-parse --abbrev-ref HEAD)/ga ; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . --target ppidd -- -j 4 ; cmake --build . -- -j 1 ; ctest -V
    - cd $TOP; BUILD=build/$(git rev-parse --abbrev-ref HEAD)/mpi ; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DPPIDD-GA=OFF -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . --target ppidd -- -j 4 ; cmake --build . -- -j 1 ; ctest -V
    - cd $TOP; ./configure --without-ga ; make ; make test; /usr/lib64/mpi/gcc/openmpi/bin/mpiexec -np 4 --allow-run-as-root test/ppidd_ctest.exe
