image: ${CI_REGISTRY}/molpro/docker

cmake_ga:
  script:
    - mkdir build && cd build
    - cmake -DMPIOPTIONS="--allow-run-as-root" ..
    - cmake --build . --target ppidd -- -j 4
    - cmake --build . -- -j 1
    - ctest -V

cmake_mpi2:
  script:
    - mkdir build && cd build
    - cmake -DPPIDD-GA=OFF -DMPIOPTIONS="--allow-run-as-root" ..
    - cmake --build . --target ppidd -- -j 4
    - cmake --build . -- -j 1
    - ctest -V

autoconf_ga:
  script:
    - ./configure --with-ga CXX=mpicxx
    - make
    - make test LIBS="-lga -larmci"
    - mpiexec -np 4 --allow-run-as-root test/ppidd_ctest.exe

autoconf_mpi2:
  script:
    - ./configure --with-mpi2 CXX=mpicxx
    - make
    - make test
    - mpiexec -np 4 --allow-run-as-root test/ppidd_ctest.exe

autoconf_serial:
  script:
    - ./configure
    - make
    - make test
    - ./test/ppidd_ctest.exe

pages:
  only:
    variables:
      - $CI_PROJECT_NAMESPACE == "molpro" && $CI_COMMIT_REF_NAME == "master"
  script:
    - ./configure
    - doxygen src/Doxyfile
    - mkdir public
    - mv doc public/
  artifacts:
    paths:
      - public
    expire_in: 1 hr

