cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths: # cache everything so that unnecessary recompilation is avoided
    - lib
    - doc
    - src
    - testjobs
    - utilities
    - CMakeLists.txt
    - tuning.com
    - build
job:
  image: pjknowles/opensuse
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l); echo $procs processors available
    - TOP=$PWD
    - git checkout $CI_COMMIT_SHA # because of cache
    - cd $TOP; BUILD=build/$(git rev-parse --abbrev-ref HEAD)/ga ; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . --target ppidd -- -j 4 ; cmake --build . -- -j 1 ; ctest -V
    - cd $TOP; BUILD=build/$(git rev-parse --abbrev-ref HEAD)/mpi ; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DPPIDD-GA=OFF -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . --target ppidd -- -j 4 ; cmake --build . -- -j 1 ; ctest -V
