image: pjknowles/opensuse

pipelines:
  default:
    - step:
        caches:
          - ppidd-cmake
        script:
          - cmake --version; g++ --version
          - TOP=$PWD; BUILD=build/$(git rev-parse --abbrev-ref HEAD)/parallel ; mkdir -p $BUILD && cd $BUILD && pwd && cmake -DMPIOPTIONS="--allow-run-as-root" $TOP
          - cmake --build . --target ppidd -- -j 4
          - cmake --build . -- -j 1 # the targets in test/ don't play well with parallel build
          - ctest -V
definitions:
  caches:
    ppidd-cmake: build
