#ifdef HAVE_CONFIG_H
#include "ppidd_config.h"
#endif

/* Map the function names to something the Fortran compiler can call */
#define PPIDD_Initialize      FC_FUNC_(ppidd_initialize,PPIDD_INITIALIZE)
#define PPIDD_Initialize_data FC_FUNC_(ppidd_initialize_data,PPIDD_INITIALIZE_DATA)
#define PPIDD_Worker_comm     FC_FUNC_(ppidd_worker_comm,PPIDD_WORKER_COMM)
#define PPIDD_Finalize        FC_FUNC_(ppidd_finalize,PPIDD_FINALIZE)
#define PPIDD_Uses_ma         FC_FUNC_(ppidd_uses_ma,PPIDD_USES_MA)
#define PPIDD_MA_init         FC_FUNC_(ppidd_ma_init,PPIDD_MA_INIT)
#define PPIDD_Wtime           FC_FUNC_(ppidd_wtime,PPIDD_WTIME)
#define PPIDD_Error           FC_FUNC_(ppidd_error,PPIDD_ERROR)
#define PPIDD_Helper_server   FC_FUNC_(ppidd_helper_server,PPIDD_HELPER_SERVER)
#define PPIDD_Nxtval          FC_FUNC_(ppidd_nxtval,PPIDD_NXTVAL)
#define PPIDD_Size_all        FC_FUNC_(ppidd_size_all,PPIDD_SIZE_ALL)
#define PPIDD_Size            FC_FUNC_(ppidd_size,PPIDD_SIZE)
#define PPIDD_Rank            FC_FUNC_(ppidd_rank,PPIDD_RANK)
#define PPIDD_Init_fence      FC_FUNC_(ppidd_init_fence,PPIDD_INIT_FENCE)
#define PPIDD_Fence           FC_FUNC_(ppidd_fence,PPIDD_FENCE)
#define PPIDD_Send            FC_FUNC_(ppidd_send,PPIDD_SEND)
#define PPIDD_Recv            FC_FUNC_(ppidd_recv,PPIDD_RECV)
#define PPIDD_Wait            FC_FUNC_(ppidd_wait,PPIDD_WAIT)
#define PPIDD_Iprobe          FC_FUNC_(ppidd_iprobe,PPIDD_IPROBE)
#define PPIDD_BCast           FC_FUNC_(ppidd_bcast,PPIDD_BCAST)
#define PPIDD_Barrier         FC_FUNC_(ppidd_barrier,PPIDD_BARRIER)
#define PPIDD_Gsum            FC_FUNC_(ppidd_gsum,PPIDD_GSUM)
#define PPIDD_Create_irreg    FC_FUNC_(ppidd_create_irreg,PPIDD_CREATE_IRREG)
#define PPIDD_Create          FC_FUNC_(ppidd_create,PPIDD_CREATE)
#define PPIDD_Destroy         FC_FUNC_(ppidd_destroy,PPIDD_DESTROY)
#define PPIDD_Distrib         FC_FUNC_(ppidd_distrib,PPIDD_DISTRIB)
#define PPIDD_Location        FC_FUNC_(ppidd_location,PPIDD_LOCATION)
#define PPIDD_Get             FC_FUNC_(ppidd_get,PPIDD_GET)
#define PPIDD_Put             FC_FUNC_(ppidd_put,PPIDD_PUT)
#define PPIDD_Acc             FC_FUNC_(ppidd_acc,PPIDD_ACC)
#define PPIDD_Read_inc        FC_FUNC_(ppidd_read_inc,PPIDD_READ_INC)
#define PPIDD_Zero_patch      FC_FUNC_(ppidd_zero_patch,PPIDD_ZERO_PATCH)
#define PPIDD_Zero            FC_FUNC_(ppidd_zero,PPIDD_ZERO)
#define PPIDD_Duplicate       FC_FUNC_(ppidd_duplicate,PPIDD_DUPLICATE)
#define PPIDD_Inquire_name    FC_FUNC_(ppidd_inquire_name,PPIDD_INQUIRE_NAME)
#define PPIDD_Inquire_stype   FC_FUNC_(ppidd_inquire_stype,PPIDD_INQUIRE_STYPE)
#define PPIDD_Inquire_mem     FC_FUNC_(ppidd_inquire_mem,PPIDD_INQUIRE_MEM)
#define PPIDD_Create_mutexes  FC_FUNC_(ppidd_create_mutexes,PPIDD_CREATE_MUTEXES)
#define PPIDD_Lock_mutex      FC_FUNC_(ppidd_lock_mutex,PPIDD_LOCK_MUTEX)
#define PPIDD_Unlock_mutex    FC_FUNC_(ppidd_unlock_mutex,PPIDD_UNLOCK_MUTEX)
#define PPIDD_Destroy_mutexes FC_FUNC_(ppidd_destroy_mutexes,PPIDD_DESTROY_MUTEXES)
#endif

#define PPIDD_LANG 2
#include "ppidd_share.h"
