name: Build and test

on:
  push:
    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master"]
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release
  AUTOCONF_TEST_TARGET: test

jobs:

  autoconf_ga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: ./configure CXX=mpicxx --with-ga

      - name: Build
        run: make

      - name: Test
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }} LIBS="-lga -larmci"
          mpiexec -np 4 test/ppidd_ctest.exe

  autoconf_mpi2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: ./configure CXX=mpicxx --with-mpi2

      - name: Build
        run: make

      - name: Test
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }}
          mpiexec -np 4 test/ppidd_ctest.exe
  

  autoconf_serial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Test
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }}
          ./test/ppidd_ctest.exe          

  cmake_ga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DPPIDD-GA=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}

      - name: Test
        run: cd ${{github.workspace}}/build && ctest -C ${{env.CMAKE_BUILD_TYPE}} || ctest -C ${{env.CMAKE_BUILD_TYPE}} --rerun-failed --output-on-failure

  cmake_mpi2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DPPIDD-GA=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}

    - name: Test
      run: cd ${{github.workspace}}/build && ctest -C ${{env.CMAKE_BUILD_TYPE}} || ctest -C ${{env.CMAKE_BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Build doxygen
      run: cmake --build ${{github.workspace}}/build --target ppidd_doc
