name: Build and test

on:
  push:
    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master"]
  workflow_dispatch:

env:
  CMAKE_BUILD_TYPE: Release
  AUTOCONF_TEST_TARGET: test

jobs:

  autoconf_ga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check existence of build configuration file
        id: check_configuration
        uses: andstor/file-existence-action@v1
        with:
          files: "configure"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: ./configure CXX=mpicxx --with-ga

      - name: Build
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: make

      - name: Test
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }} LIBS="-lga -larmci"
          mpiexec -np 4 test/ppidd_ctest.exe

  autoconf_mpi2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check existence of build configuration file
        id: check_configuration
        uses: andstor/file-existence-action@v1
        with:
          files: "configure"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: ./configure CXX=mpicxx --with-mpi2

      - name: Build
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: make

      - name: Test
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }}
          mpiexec -np 4 test/ppidd_ctest.exe
  

  autoconf_serial:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check existence of build configuration file
        id: check_configuration
        uses: andstor/file-existence-action@v1
        with:
          files: "configure"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: ./configure

      - name: Build
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: make

      - name: Test
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: |
          make ${{ env.AUTOCONF_TEST_TARGET }}
          ./test/ppidd_ctest.exe          

  cmake_ga:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Check existence of build configuration file
        id: check_configuration
        uses: andstor/file-existence-action@v1
        with:
          files: "CMakeLists.txt"

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure CMake
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DPPIDD-GA=ON

      - name: Build
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}

      - name: Test
        if: steps.check_configuration.outputs.files_exists == 'true'
        run: cd ${{github.workspace}}/build && ctest -C ${{env.CMAKE_BUILD_TYPE}} || ctest -C ${{env.CMAKE_BUILD_TYPE}} --rerun-failed --output-on-failure

  cmake_mpi2:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      # relies on repository name being all lower case
      image: ghcr.io/${{ github.repository }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Check existence of build configuration file
      id: check_configuration
      uses: andstor/file-existence-action@v1
      with:
        files: "CMakeLists.txt"

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Configure CMake
      if: steps.check_configuration.outputs.files_exists == 'true'
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DPPIDD-GA=OFF

    - name: Build
      if: steps.check_configuration.outputs.files_exists == 'true'
      run: cmake --build ${{github.workspace}}/build --config ${{env.CMAKE_BUILD_TYPE}}

    - name: Test
      if: steps.check_configuration.outputs.files_exists == 'true'
      run: cd ${{github.workspace}}/build && ctest -C ${{env.CMAKE_BUILD_TYPE}} || ctest -C ${{env.CMAKE_BUILD_TYPE}} --rerun-failed --output-on-failure

    - name: Build doxygen
      run: cmake --build ${{github.workspace}}/build --target ppidd_doc
